# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

randomSample <- function(N, m = -1L) {
    .Call('randomizr_randomSample', PACKAGE = 'randomizr', N, m)
}

simulator <- function(N, m, t) {
    .Call('randomizr_simulator', PACKAGE = 'randomizr', N, m, t)
}

